name: CD_HOMOLOG
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_HML }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_HML }}

on:
  push:
    branches: [results]

defaults:
  run:
    shell: bash

jobs:
  deploy_homolog_and_dast:
    environment: homolog
    name: 'Deploy to homolog and DAST tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Config GitHub
        run: |
          git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER_NAME}}"

      - name: Install Node.js
        uses: actions/setup-node@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
  
      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: |
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      # DAST

      #ZAP BASELINE SCAN
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.TOKEN_GIT }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://hml-tcc-password-manager.vercel.app'
          cmd_options: '-a'
          allow_issue_writing: 'true'
          artifact_name: 'zap_baseline_scan'

      - name: Upload Zap Baseline Scan Report to Action
        uses: actions/upload-artifact@v4
        with:
          name: zap_baseline_scan
          path: |
            ${{ github.workspace }}/report_html.html
            ${{ github.workspace }}/report_md.md
            ${{ github.workspace }}/report_json.json

      - name: Save ZAP Baseline Scan Reports
        if: always()
        run: |
          git clone "https://x-access-token:${{secrets.TOKEN_GIT}}@github.com/tcc-lucas-dafne/${{secrets.NAME_REPO_GIT}}" ${{secrets.NAME_REPO_GIT}}
          cd ${{secrets.NAME_REPO_GIT}}
          git checkout develop
          current_date=$(date +%Y-%m-%d)
          rm -rf reports/zap_baseline_scan/${current_date} && mkdir -p reports/zap_baseline_scan/${current_date}
          cp -R ${{github.workspace}}/report_html.html reports/zap_baseline_scan/${current_date}/
          cp -R ${{github.workspace}}/report_json.json reports/zap_baseline_scan/${current_date}/
          cp -R ${{github.workspace}}/report_md.md reports/zap_baseline_scan/${current_date}/
          git add .
          git commit -m "Adicionando relatório no repositório ${{ github.event.repository.name }} ${{ github.ref_name }} [skip ci]"
          git push origin develop
          
      - name: Remove ZAP Baseline Reports 
        run: |
          rm report_html.html
          rm report_md.md
          rm report_json.json

      #ZAP FULL SCAN
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.TOKEN_GIT }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://hml-tcc-password-manager.vercel.app'
          cmd_options: '-a'
          allow_issue_writing: 'true'
          artifact_name: 'zap_full_scan'

      - name: Upload Zap Full Scan Report to Action
        uses: actions/upload-artifact@v4
        with:
          name: zap_full_scan
          path: |
            ${{ github.workspace }}/report_html.html
            ${{ github.workspace }}/report_md.md
            ${{ github.workspace }}/report_json.json

      - name: Save ZAP Full Scan Reports
        if: always()
        run: |
          git clone "https://x-access-token:${{secrets.TOKEN_GIT}}@github.com/tcc-lucas-dafne/${{secrets.NAME_REPO_GIT}}" ${{secrets.NAME_REPO_GIT}}
          cd ${{secrets.NAME_REPO_GIT}}
          git checkout develop
          current_date=$(date +%Y-%m-%d)
          rm -rf reports/zap_full_scan/${current_date} && mkdir -p reports/zap_full_scan/${current_date}
          cp -R ${{github.workspace}}/report_html.html reports/zap_full_scan/${current_date}/
          cp -R ${{github.workspace}}/report_json.json reports/zap_full_scan/${current_date}/
          cp -R ${{github.workspace}}/report_md.md reports/zap_full_scan/${current_date}/
          git add .
          git commit -m "Adicionando relatório no repositório ${{ github.event.repository.name }} ${{ github.ref_name }} [skip ci]"
          git push origin develop

      - name: Remove ZAP Full Scan Reports 
        run: |
          rm report_html.html
          rm report_md.md
          rm report_json.json

      # NIKTO
      - name: Create nikto report file
        run: |
          touch ${{ github.workspace }}/nikto_out.json
          chmod o+w ${{ github.workspace }}/nikto_out.json
          chmod g+w ${{ github.workspace }}/nikto_out.json

      - name: Find absolute path of nikto_out.json
        id: find_file_path
        run: |
          # Encontra o caminho absoluto do arquivo nikto_out.json
          file_path=$(realpath nikto_out.json)
          echo "FILE_PATH=$file_path" >> $GITHUB_ENV

      - name: Scan with nikto
        uses: thereisnotime/action-nikto@master
        with:
          url: "https://hml-tcc-password-manager.vercel.app/"
          additional_args: "-Option FAILURES=0 -o $FILE_PATH -Format json"

      - name: Upload Nikto Report to Action
        uses: actions/upload-artifact@v4
        with:
          name: nikto-report
          path: ${{ runner.temp }}/nikto_out.json
      
      - name: Save Nikto Report
        if: always()
        run: |
          git clone "https://x-access-token:${{secrets.TOKEN_GIT}}@github.com/tcc-lucas-dafne/${{secrets.NAME_REPO_GIT}}" ${{secrets.NAME_REPO_GIT}}
          cd ${{secrets.NAME_REPO_GIT}}
          git checkout develop
          current_date=$(date +%Y-%m-%d)
          rm -rf reports/nikto/${current_date} && mkdir -p reports/nikto/${current_date}
          cp -R ${{github.workspace}}/nikto_out.json reports/nikto/${current_date}/
          git add .
          git commit -m "Adicionando relatório no repositório ${{ github.event.repository.name }} ${{ github.ref_name }} [skip ci]"
          git push origin develop
